import "./globals.css";
import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import { MetaMaskProvider } from "../contexts/meta-maks.context";
import { AuthProvider } from "../contexts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {

  return (
    <html lang="en">
      <MetaMaskProvider>
      <AuthProvider>
        <body className={inter.className}>{children}</body>
      </AuthProvider>
      </MetaMaskProvider>
    </html>
  );
}
